apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f C:\Users\Matthew.Anderson\source\repos\sextant\sextant\docker-compose.yml
      -o ./sextant/kube
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: plantuml
  name: plantuml
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  selector:
    io.kompose.service: plantuml
status:
  loadBalancer: {}
