apiVersion: v1
kind: Service
metadata:
  annotations:
    app: plant-uml
  creationTimestamp: null
  labels:
    app: plantuml
  name: plantuml

spec:
  type: LoadBalancer
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  selector:
    io.kompose.service: plantuml
