apiVersion: v1
kind: Service
metadata:
  annotations:
    app: plant-uml
  creationTimestamp: null
  labels:
    app: plantuml
  name: plantuml
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  selector:
    io.kompose.service: plantuml
status:
  loadBalancer: {}
