apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f C:\Users\Matthew.Anderson\source\repos\sextant\sextant\docker-compose.yml
      -o ./sextant/kube
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: plantuml
  name: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plantuml
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f C:\Users\Matthew.Anderson\source\repos\sextant\sextant\docker-compose.yml
          -o ./sextant/kube
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: plantuml
    spec:
      containers:
      - image: plantuml/plantuml-server:tomcat
        imagePullPolicy: ""
        name: plantuml
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
