apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: plant-uml
  creationTimestamp: null
  labels:
    io.kompose.service: plantuml
  name: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plantuml
  strategy: {}
  template:
    metadata:
      annotations:
        app: plant-uml
      creationTimestamp: null
      labels:
        io.kompose.service: plantuml
    spec:
      containers:
      - image: plantuml/plantuml-server:tomcat
        imagePullPolicy: ""
        name: plantuml
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
