apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f C:\Users\Matthew.Anderson\source\repos\sextant\sextant\docker-compose.yml
      -o ./sextant/kube
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sextant
  name: sextant
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 7654
    targetPort: 80
  selector:
    io.kompose.service: sextant
status:
  loadBalancer: {}
