apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: sextant
  creationTimestamp: null
  labels:
    io.kompose.service: sextant
  name: sextant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sextant
  strategy: {}
  template:
    metadata:
      annotations:
        app: sextant
      creationTimestamp: null
      labels:
        io.kompose.service: sextant
    spec:
      containers:
      - image: docker.io/library/sextant:dev
        imagePullPolicy: ""
        name: sextant
        env:
        - name: PLANT_UML_SERVER
          value: http://127.0.0.1:8080
        ports:
        - containerPort: 80
        resources: {}
      - image: plantuml/plantuml-server:tomcat
        env:
          - name: PLANTUML_LIMIT_SIZE
            value: '8192'
        imagePullPolicy: ""
        name: plantuml
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
