apiVersion: v1
kind: Service
metadata:
  annotations:
    app: sextant
  creationTimestamp: null
  labels:
   app: sextant
  name: sextant
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 7654
    targetPort: 80
  selector:
    io.kompose.service: sextant
status:
  loadBalancer: {}
