apiVersion: v1
kind: Service
metadata:
  labels:
    app: sextant
  name: sextant
  namespace: default
spec:
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: sextant